[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.8.0",
    "anyio==4.14.2",
    "certifi==2026.7.22",
    "flatbuffers==25.12.19",
    "grpcio==1.83.0",
    "h11==0.16.0",
    "h2==4.4.0",
    "hpack==4.2.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "hyperframe==6.1.0",
    "idna==3.18",
    "networkx==3.6.1",
    "numpy==2.5.1",
    "ollama==0.6.2",
    "onnxruntime==1.28.0",
    "packaging==26.2",
    "portalocker==3.2.0",
    "protobuf==7.35.1",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "pymupdf==1.28.0",
    "pymupdf-layout==1.28.0",
    "pymupdf4llm==1.28.0",
    "pywin32==312",
    "pyyaml==6.0.3",
    "qdrant-client==1.18.0",
    "tabulate==0.10.0",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.2",
    "urllib3==2.7.0",
]
